ci/cd: fix enter rollback with bridge job & auto deploy for test pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -163,15 +163,30 @@ deploy:
       EOF
   environment:
     name: staging
-  when: manual
   only:
     - main
+
+rollback_input:
+  stage: deploy
+  when: manual
+  variables:
+    ROLLBACK_TAG: ""
+  script:
+    - |
+      if [ -z "$ROLLBACK_TAG" ]; then
+        echo "ERROR: Please set ROLLBACK_TAG when running this job from UI"
+        exit 1
+      fi
+    - echo "ROLLBACK_TAG=$ROLLBACK_TAG" > rollback.env
+  artifacts:
+    reports:
+      dotenv: rollback.env
 
 rollback:
   stage: deploy
   image: alpine:${ALPINE_VERSION}
-  variables:
-    ROLLBACK_TAG: ""
+  needs:
+    - rollback_input
   before_script:
     - apk add --no-cache openssh curl
     - mkdir -p ~/.ssh
@@ -322,5 +337,3 @@ rollback:
       EOF
   only:
     - main
-  when: manual
-  allow_failure: false
